* MFT: Long-Term Tracking of Every Pixel
[[https://cmp.felk.cvut.cz/~serycjon/MFT/][Project Page]]
Official implementation of the MFT tracker from the paper:

[[https://scholar.google.com/citations?user=fK9nkmQAAAAJ&hl=en&oi=ao][Michal Neoral]], [[https://cmp.felk.cvut.cz/~serycjon/][Jonáš Šerých]], [[https://cmp.felk.cvut.cz/~matas/][Jiří Matas]]: "*MFT: Long-Term Tracking of Every Pixel*", WACV 2024

Please cite our paper, if you use any of this.
#+begin_example
@inproceedings{neoral2024mft,
               title={{MFT}: Long-Term Tracking of Every Pixel},
               author={Neoral, Michal and {\v{S}}er{\`y}ch, Jon{\'a}{\v{s}} and Matas, Ji{\v{r}}{\'\i}},
               journal={arXiv preprint arXiv:2305.12998},
               year={2023},
}
#+end_example
** Install
Create and activate a new virtualenv:
#+BEGIN_SRC sh
# we have tested with python 3.7.4
python -m venv venv
source venv/bin/activate
#+END_SRC

Then install all the dependencies:
#+BEGIN_SRC sh
pip install torch numpy einops tqdm opencv-python scipy Pillow==9 matplotlib ipdb
#+END_SRC

** Run the demo
Simply running:
#+BEGIN_SRC sh
python demo.py
#+END_SRC

should produce a ~demo_out~ directory with two visualizations.

** Training
See [[file:train.org][train.org]]
** License
The demo video in ~demo_in~ was extracted from [[https://www.youtube.com/watch?v=ugsJtsO9w1A][youtube]].

This work is licensed under the [[https://creativecommons.org/licenses/by-nc-sa/4.0/][Attribution-NonCommercial-ShareAlike 4.0 International]] license.
The ~MFT/RAFT~ directory contains a modified version of [[https://github.com/princeton-vl/RAFT][RAFT]], which is licensed under BSD-3-Clause license.
Our modifications (~OcclusionAndUncertaintyBlock~ and its integration in ~raft.py~) are licensed again under the [[https://creativecommons.org/licenses/by-nc-sa/4.0/][Attribution-NonCommercial-ShareAlike 4.0 International]].

** Acknowledgments
This work was supported by Toyota Motor Europe,
by the Grant Agency of the Czech Technical University in Prague, grant No. ~SGS23/173/OHK3/3T/13~, and
by the Research Center for Informatics project ~CZ.02.1.01/0.0/0.0/16_019/0000765~ funded by OP VVV.
